/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-system-bootstrap": require("reakit-system-bootstrap"),
  "reakit-system-bootstrap/palette": require("reakit-system-bootstrap/palette"),
  "reakit-system-bootstrap/Tabbable": require("reakit-system-bootstrap/Tabbable"),
  "reakit-system-bootstrap/Button": require("reakit-system-bootstrap/Button"),
  "reakit-system-bootstrap/Box": require("reakit-system-bootstrap/Box")
};
