/* eslint-disable */
// Automatically generated by ../../../../scripts/build/utils.js
export default {
  "reakit-system-bootstrap": require("reakit-system-bootstrap"),
  "reakit-system-bootstrap/utils/useStyle": require("reakit-system-bootstrap/utils/useStyle"),
  "reakit-system-bootstrap/utils": require("reakit-system-bootstrap/utils"),
  "reakit-system-bootstrap/system/useButton": require("reakit-system-bootstrap/system/useButton"),
  "reakit-system-bootstrap/system/useBox": require("reakit-system-bootstrap/system/useBox"),
  "reakit-system-bootstrap/system/palette": require("reakit-system-bootstrap/system/palette"),
  "reakit-system-bootstrap/system": require("reakit-system-bootstrap/system")
};
